// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"
)

type Message struct {
	ID        int64
	ClientID  string
	Topic     string
	Payload   []byte
	Timestamp time.Time
}
