mqtt:
  host: 127.0.0.1
  port: 1883

rest:
  host: 127.0.0.1
  port: 4444

database:
  path: "db/room-read.db"
  name: room-read
  migrationPath: "migrations"

logging:
  level: debug
  prettyPrint: true
